version: '2'
services:
  data:
    volumes:
      - ./db-dev/:/data-dev/
  db:
    volumes_from:
      - data
    depends_on:
      - data
    ports:
      - 3306:3306
  node-app:
    ports:
      - "6000:8000"
    volumes_from:
      - data
    depends_on:
      - data
      - db
  web-server:
    ports:
      - "60:80"
    volumes_from:
      - data
    depends_on:
      - data
      - node-app
