version: '2'
services:
  data:
    image: ubuntu:latest
  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    depends_on:
      - data
  node-app:
    build: .
    depends_on:
      - data
      - db
  web-server:
    build: 
       context: .
       dockerfile: Dockerfile.web
    depends_on:
      - data
      - node-app
